language: node_js
node_js:
  - "4"
  
jdk:
  - oraclejdk8
  
addons:
  apt:
    packages:
      - oracle-java8-installer
  sonarqube: true
   
before_script:
    - cd BrainsGroup
    - npm install
    - export JAVA_HOME=/usr/lib/jvm/java-8-oracle
    
env:
  global:
    - secure:582e67217eefd2fff9a0db381c59ca3afd6336af

script: 
  - npm test
  - cd ..
  - sonar-scanner -Dsonar.login=$SONAR_TOKEN

branches:
  only:
    - master

notifications:
  slack: luna-org:y6ylXOrxL8Yt6PCi8yDVMjWV
