language: node_js
node_js:
  - "4"
  
jdk:
  - oraclejdk8
  
addons:
  apt:
    packages:
      - oracle-java8-installer
  sonarqube: true
   
before_script:
    - cd BrainsGroup
    - npm install
    - export JAVA_HOME=/usr/lib/jvm/java-8-oracle

script: 
  - npm test
  - cd ..
  - rm -rf BrainsGroup/node_modules
  - sonar-scanner
  

branches:
  only:
    - master

notifications:
  slack: luna-org:y6ylXOrxL8Yt6PCi8yDVMjWV
