language: node_js
node_js:
  - "4"

before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - wget http://repo1.maven.org/maven2/org/codehaus/sonar/runner/sonar-runner-dist/2.4/sonar-runner-dist-2.4.zip
    - unzip sonar-runner-dist-2.4.zip

before_script:
    - cd BrainsGroup
    - npm install

script: npm test

branches:
  only:
    - master
    - Testes

after_script:
 - ./sonar-runner-2.4/bin/sonar-runner

notifications:
  slack: luna-org:y6ylXOrxL8Yt6PCi8yDVMjWV
